[cv]
name = "胡图图"
email = "tutuhu@gmail.com"
phone = "(+86) 820-820-8820"
website = "https://www.wikiwand.com/zh/大耳朵图图"
birthday = "2000.06.21"
# 路径
avatar = ""

[[educations]]
school = "翻斗幼儿园"
major = "软件工程"
degree = "幼儿园"
date = "2006.9 - now"

[[educations]]
school = "翻斗学前班"
major = "计算机科学与技术"
degree = "学前班"
date = "2003.9 - 2006.6"

[[projects]]
name = "Kubernetes"
url = "https://github.com/kubernetes/kubernetes"
date = "2014.6 - now"
desc = "Kubernetes是一个开源的，用于管理云平台中多个主机上的容器化的应用"
points = ["负责Kubernetes的网络部分", "负责Kubernetes的不知道什么部分"]

[[projects]]
name = "Linux"
url = "https://github.com/torvalds/linux"
date = "2006.6 - 2022.6"
desc = "Linux是一个开源的操作系统内核"
points = [
    "负责Linux的文件系统部分，包括ext4, btrfs, xfs, f2fs",
    "负责Linux的网络部分，包括TCP/IP, UDP, SCTP, DCCP, IPv4, IPv6",
]

[[projects]]
name = "翻斗幼儿园每日打卡"
url = ""
date = "2019.12 - 2023.1"
desc = ""
points = ["可以进行翻斗幼儿园每日打卡", "在线用户超过20"]

[[internships]]
company = "翻斗大街翻斗花园2号楼"
jobtitle = "端茶倒水"
date = "2022.4 - 2022.6"
points = ["负责端茶倒水", "负责浇花"]

[[internships]]
company = "翻斗幼儿园"
jobtitle = "扮演小学生"
date = "2022.4 - 2022.6"
points = ["和张小帅一起玩", "和张小帅一起吃饭", "和张小帅一起睡觉(误)"]

[[awards]]
name = "最佳编导奖（获奖）"
date = "2006.11.8"

[[awards]]
name = "优秀长篇美术片奖（获奖）"
date = "2006.11.8"

[[awards]]
name = "中国电视艺术最高政府奖 - 星光奖"
date = "2010.1.24"

[[skills]]
name = "编程语言"
desc = "C/C++, Python, Java, JavaScript, HTML/CSS, PHP, SQL"

[[skills]]
name = "工具"
desc = "Git, Vim, VS Code, Linux, Docker, MySQL, MongoDB, Redis"

[[skills]]
name = "语言"
desc = "中文, 英语, 日语, 俄语, 法语, 德语, 西班牙语, 阿拉伯语, 葡萄牙语, 意大利语, 希腊语, 土耳其语"
